const { writeFile } = require('fs');
const { argv } = require('yargs');
const { version } = require('../package.json');

// read environment variables from .env file
require('dotenv').config();

const { environment } = argv;
const isProduction = environment === 'prod';
const targetPath = `./src/environments/environment${
  isProduction ? '.prod' : ''
}.ts`;

const environmentFileContent = `// Autogenerated from .env file by setenv.ts script

export const environment = {
  production: ${isProduction},
  VERSION: '${version}',
  API_URL: '${process.env.API_URL}',
  YMAPS_APIKEY: '${process.env.YMAPS_APIKEY}',
};
`;

writeFile(targetPath, environmentFileContent, (err: any) => {
  if (err) console.log(err);
  console.log(`Wrote variables to ${targetPath}`);
});
