name: Deploy2Prod

on:
  push:
    branches:
      - main

env:
  API_URL: ${{ secrets.API_URL }}
  YMAPS_APIKEY: ${{ secrets.YMAPS_APIKEY }}
  ASSETS_URL: https://excurs-orel.ru/guidebook/dist/exogb/browser/assets/

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run test:prod
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # Setup key
      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "${{ secrets.key }}" > "$HOME/.ssh/key"
      - run: chmod 600 "$HOME/.ssh/key"
      # Build
      - run: npm ci
      - run: npm run build:prod
      # Deploy
      - run: rsync -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete deploy/. denkiril@denkiril.beget.tech:~/excurs-orel.ru/public_html/
      - run: rsync -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete deploy/prod/guidebook/. denkiril@denkiril.beget.tech:~/excurs-orel.ru/public_html/guidebook/
      - run: rsync -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete dist/exogb/. denkiril@denkiril.beget.tech:~/excurs-orel.ru/public_html/guidebook/dist/exogb/
      - run: touch denkiril@denkiril.beget.tech:~/dev.excurs-orel.ru/public_html/guidebook/tmp/restart.txt
